name: 'Bepo - PR Duplicate Detection'
description: 'Detect duplicate pull requests using static analysis'
author: 'Andrew Park'

branding:
  icon: 'copy'
  color: 'orange'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: '${{ github.token }}'
  threshold:
    description: 'Similarity threshold (0.0-1.0)'
    required: false
    default: '0.65'
  limit:
    description: 'Max PRs to compare against'
    required: false
    default: '50'
  comment:
    description: 'Post a comment on the PR if duplicates found'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install bepo
      shell: bash
      run: pip install bepo

    - name: Check for duplicates
      id: check
      shell: bash
      env:
        GH_TOKEN: '${{ inputs.github-token }}'
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        
        echo "Checking PR #$PR_NUMBER for duplicates..."
        
        # Run bepo and capture output
        OUTPUT=$(bepo check-pr --repo "$REPO" --pr "$PR_NUMBER" --threshold ${{ inputs.threshold }} --limit ${{ inputs.limit }} --json 2>/dev/null || echo '{"matches":[]}')
        
        # Count matches
        MATCH_COUNT=$(echo "$OUTPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(len(d.get('matches',[])))")
        
        echo "matches=$OUTPUT" >> $GITHUB_OUTPUT
        echo "match_count=$MATCH_COUNT" >> $GITHUB_OUTPUT
        
        if [ "$MATCH_COUNT" -gt 0 ]; then
          echo "Found $MATCH_COUNT potential duplicate(s)"
          echo "has_duplicates=true" >> $GITHUB_OUTPUT
        else
          echo "No duplicates found"
          echo "has_duplicates=false" >> $GITHUB_OUTPUT
        fi

    - name: Post comment
      if: steps.check.outputs.has_duplicates == 'true' && inputs.comment == 'true'
      uses: actions/github-script@v7
      with:
        github-token: '${{ inputs.github-token }}'
        script: |
          const matches = JSON.parse(process.env.MATCHES);
          
          if (!matches.matches || matches.matches.length === 0) return;
          
          let body = '## ⚠️ Potential Duplicate PRs Detected\n\n';
          body += 'This PR may be similar to existing open PRs:\n\n';
          body += '| PR | Similarity | Reason |\n';
          body += '|---|---|---|\n';
          
          for (const m of matches.matches.slice(0, 5)) {
            const prNum = m.pr.replace('#', '');
            body += `| [${m.pr}](${context.payload.repository.html_url}/pull/${prNum}) | ${Math.round(m.similarity * 100)}% | ${m.reason} |\n`;
          }
          
          if (matches.matches.length > 5) {
            body += `\n*...and ${matches.matches.length - 5} more*\n`;
          }
          
          body += '\n---\n*Detected by [bepo](https://github.com/aardpark/bepo)*';
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: body
          });
      env:
        MATCHES: '${{ steps.check.outputs.matches }}'

outputs:
  has_duplicates:
    description: 'Whether duplicates were found'
    value: '${{ steps.check.outputs.has_duplicates }}'
  match_count:
    description: 'Number of duplicate matches'
    value: '${{ steps.check.outputs.match_count }}'
  matches:
    description: 'JSON array of matches'
    value: '${{ steps.check.outputs.matches }}'
